# -*- coding: utf-8 -*-
"""Done Web Scraping- Amazon Reviews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EW6kmtqjxwU73Nt4FoU8kcok2AkyKVtd
"""

# Scraping the Review Content from Amazon

''' Importing Beautiful Soup Library for Web Scraping and requests to get data from the URL'''

from bs4 import BeautifulSoup
import requests

r = requests.get("https://www.amazon.in/Apple-iPhone-11-128GB-Black/product-reviews/B07XVLW7YK/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews")

''' To print the URL that we search for along with Query '''
print(r.url)

''' This will print the HTML content of the web page which doesn't look like HTML format though but I further use the prettify() function to print the content in HTML format. '''

print(r.content)

''' By default we have to give HTML parser '''
soup = BeautifulSoup(r.text, 'html.parser')

''' Use prettify to make the HTML code look better.'''
print(soup.prettify())

Name = soup.findAll("span", {"class" : "a-profile-name"})     # find <span> element with attributes class = a-profile-name

# Extract name from span tag
Reviewer = []
for i in range(5,len(Name)):     # Loop is initiated from 2 because we have to exclude the Top Positive and Top Critical Review which otherwise will get repeated.
    Reviewer.append(Name[i].get_text())
    
print(Reviewer)

Product_Rating = soup.findAll("i", {"class" : "review-rating"})     # find <i> element with attributes class = review-rating

# Extract name from span tag
Rating = []
for i in range(2,len(Product_Rating)):     # Loop is initiated from 2 because we have to exclude the Top Positive and Top Critical Review which otherwise will get repeated.
    Rating.append(Product_Rating[i].get_text())
    
print(Rating)

Review_Title = soup.findAll("a", {"class" : "review-title-content"})     # find <a> element with attributes class = review-title-content

# Extract name from span tag
Review_Summary = []
for i in range(0,len(Review_Title)):
    Review_Summary.append(Review_Title[i].get_text())

# We will remove the '\n' from before and after of every Review Title
Review_Summary[:] = [i.lstrip('\n').rstrip('\n') for i in Review_Summary]

print(Review_Summary)

Review_Description = soup.findAll("span", {"class" : "review-text-content"})     # find <span> element with attributes class = review-text-content

# Extract name from span tag
Description = []
for i in range(0,len(Review_Description)):
    Description.append(Review_Description[i].get_text())

# We will remove the '\n' from before and after of every Review Desciption
Description[:] = [i.lstrip('\n').rstrip('\n') for i in Description]

print(Description)

# Saving the Scraped Content to .csv file from

import pandas as pd

# Make a DataFrame to add Details in it
Data = pd.DataFrame()

# Adding Review Information in DataFrame

Data["Reviewer"] = Reviewer
Data["Rating"] = Rating
Data["Review Title"] = Review_Summary
Data["Review Description"] = Description

Data

# Converting DataFrame to .csv file and Saving it in your Machine

Data.to_csv(r'C:\Users\lenovo\python\reviews.csv', index= 'True')

